#!/usr/bin/env arch -x86_64 bash
#
# Wrapper script for winetricks compatability
#
# Copyright (C) 2021 Dean M Greer
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
#

export CX_INSTALL="${CX_INSTALL:-/Applications/CrossOver.app}"; export CX_WINEPATH="${CX_INSTALL}/Contents/SharedSupport/CrossOver/bin"
if [ ! command -v "${CX_WINEPATH}/wine" &> /dev/null ]; then
    echo "CrossOver not found"; exit
fi

export CX_BOTTLE="${CX_BOTTLE:-$HOME/Library/Application Support/CrossOver/Bottles/default}"
if [ ! -d "${CX_BOTTLE}" ]; then
    echo "Please set \$CX_BOTTLE env to your CrossOver Bottle"; exit
fi

if [ ! -f "$(dirname $0)/winetricks-macOS" &> /dev/null ]; then
    curl -Lo "$(dirname $0)/winetricks-macOS" https://raw.githubusercontent.com/Gcenx/winetricks/macOS/src/winetricks
    chmod +x "$(dirname $0)/winetricks-macOS"
fi

export PATH=${CX_WINEPATH}:${PATH}

exec "$(dirname $0)/winetricks-macOS" "${@}"
