#!/bin/sh

export ARGS="$@"
export WINE="@@APPDIR@@/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine"
export WINE64="@@APPDIR@@/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine"

export CX_BOTTLE="${CX_BOTTLE:-$HOME/Library/Application Support/CrossOver/Bottles/default}"
export WINEPREFIX=${CX_BOTTLE}

exec "@@PREFIX@@/bin/winetricks" "${@}"
