#!/bin/sh
#
# Wrapper script for winetricks compatability
#
# Copyright (C) 2021 Dean M Greer
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA

export CX_BOTTLE="${CX_BOTTLE:-$HOME/Library/Application Support/CrossOver/Bottles/default}"
if [ ! -d "${CX_BOTTLE}" ]; then
    echo "Please set \$CX_BOTTLE env to your CrossOver Bottle"; exit
fi

export CX_PATH="/Applications/CrossOver.app/Contents/SharedSupport/CrossOver"
export WINE=wine
export WINE64=wine
export WINESERVER=wineserver
export WINEPREFIX="${CX_BOTTLE}"
export WINETRICKS_WINE_VERSION=$(sed -n '2p' "${CX_PATH}/share/wine/wine.inf" | tr ' ' '\a' | awk -F'\a' '{print $4}')
export WINEDEBUG=-all

exec winetricks -q "${@}"
